import { mkdir, copyFile, readFile, writeFile } from "node:fs/promises";
await mkdir("assets/fonts", { recursive: true });
await mkdir("assets/vendor", { recursive: true });
await mkdir("assets/licenses", { recursive: true });
for (const font of ["manrope", "eb-garamond"]) {
  for (const subset of ["latin", "latin-ext"])
    await copyFile(
      `node_modules/@fontsource-variable/${font}/files/${font}-${subset}-wght-normal.woff2`,
      `assets/fonts/${font}-${subset}.woff2`,
    );
  await copyFile(
    `node_modules/@fontsource-variable/${font}/LICENSE`,
    `assets/licenses/${font}.txt`,
  );
}
for (const name of ["gsap"])
  await copyFile(
    `node_modules/gsap/dist/${name}.min.js`,
    `assets/vendor/${name}.min.js`,
  );
await writeFile(
  "assets/licenses/gsap.txt",
  "GSAP, Copyright GreenSock. Standard license: https://gsap.com/standard-license/\nOriginal copyright notices are preserved in the distributed files.\n",
);
await copyFile(
  "node_modules/@phosphor-icons/core/LICENSE",
  "assets/licenses/phosphor.txt",
);
const names = [
  "arrow-up-right",
  "arrow-right",
  "arrow-left",
  "sun",
  "moon",
  "list",
  "x",
  "graph",
  "squares-four",
  "play",
  "pause",
  "corners-out",
  "plus",
  "minus",
  "skip-back",
  "caret-left",
  "caret-right",
  "check",
  "flask",
  "download-simple",
];
const icons = {};
for (const name of names)
  icons[name] = (
    await readFile(
      `node_modules/@phosphor-icons/core/assets/regular/${name}.svg`,
      "utf8",
    )
  ).replace("<svg ", '<svg aria-hidden="true" class="icon" ');
await writeFile(
  "js/icons.js",
  `/* Phosphor Icons, MIT. Generated by scripts/vendor.mjs. */\nwindow.GraphosIcons = ${JSON.stringify(icons)};\n`,
);
